apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.goharbor.io
    chart: harbor
    targetRevision: 1.15.0
    helm:
      valuesObject:
        expose:
          type: ingress
          ingress:
            hosts:
              core: harbor.metube.dk
            annotations:
              kubernetes.io/ingress.class: traefik
              traefik.ingress.kubernetes.io/redirect-entry-point: https
              cert-manager.io/cluster-issuer: letsencrypt-prod
          tls:
            enabled: true
            certSource: secret
            secret:
              secretName: harbor-tls
        externalURL: "https://harbor.metube.dk"
  destination:
    server: https://kubernetes.default.svc
    namespace: harbor
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

