apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.goharbor.io
    chart: harbor
    targetRevision: 1.15.0
    helm:
      valuesObject:
        expose:
          type: ingress
          ingress:
            hosts:
              core: harbor.metube.dk
            annotations: {}
          tls:
            enabled: false
        externalUrl: "http://harbor.metube.dk"
  destination:
    server: https://kubernetes.default.svc
    namespace: harbor
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

