apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backstage
  namespace: argocd
spec:
  project: default

  # Use the official Backstage Helm chart
  source:
    repoURL: https://backstage.github.io/charts
    chart: backstage
    targetRevision: "*"
    helm:
      valueFiles:
        - $values/backstage/values.yaml

  # Pull values.yaml from your own repo
  sources:
    - repoURL: https://github.com/andreasfrisch/cluster-apps.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: backstage

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

